--DEPT_CODE가 D9이거나 D6이고 SALARY가 300만원 이상인 사원의 EMP_NAME, EMP_NO, DEPT_CODE, SALARY를 조회
SELECT EMP_NAME, EMP_NO, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE (DEPT_CODE = 'D9' OR DEPT_CODE = 'D6') AND SALARY >= 3000000;