--문제
--1. 조인의 종류(10점) 
--2. 해당 문제가 발생한 원인(20점)을 원인에 기술하고
--3. 해결할 수 있는 조치사항(20점)
--4. 조치사항이 적용된 ANSI 구문(20점)
--5. 오라클 전용 구문으로 변경(30점)하여 조치내용에 기술하시오.

--사용한 테이블 생성 정보
CREATE TABLE DEPARTMENT(
    DEPTCODE NUMBER,
    DEPTNAME VARCHAR2(10)
);

CREATE TABLE EMPLOYEE(
    EMPNO NUMBER,
    EMPNAME VARCHAR2(10),
    DEPTNO NUMBER
);

--정보 추가
INSERT INTO DEPARTMENT VALUES (1, '개발팀');
INSERT INTO DEPARTMENT VALUES (2, '경영팀');

INSERT INTO EMPLOYEE VALUES (101, '임예은', 1);
INSERT INTO EMPLOYEE VALUES (102, '이나경', 2);
INSERT INTO EMPLOYEE VALUES (103, '서지훈', 1);

--실행한 조인 쿼리
--문제사항 발생(ORA-00904: "DEPARTMENT"."DEPTNO": invalid identifier)
SELECT EMPNO, EMPNAME, DEPTNO, DEPTNAME
FROM EMPLOYEE JOIN DEPARTMENT 
USING (DEPTNO);
--조치 후, ANSI 구문 : INNER JOIN ~ ON
SELECT b.EMPNO, b.EMPNAME, b.DEPTNO, a.DEPTNAME
FROM DEPARTMENT a JOIN EMPLOYEE b
    ON a.DEPTCODE = b.DEPTNO;
--오라클 전용 구문(동등조인)
SELECT b.EMPNO, b.EMPNAME, b.DEPTNO, a.DEPTNAME
FROM DEPARTMENT a, EMPLOYEE b
WHERE a.DEPTCODE = b.DEPTNO;
