--일반 사용자 계정인 TEST 계정으로 접속하여 계정이 SAMPLE 비밀번호가 1234인 계정을 생성
CREATE USER SAMPLE IDENTIFIED BY 1234;

--인증 권한 부여
GRANT CREATE SESSION TO SAMPLE; 

--테이블 생성 권한 부여
GRANT CREATE TABLE, RESOURCE TO SAMPLE;

--데이터 조작 권한 부여
GRANT CONNECT, DBA TO SAMPLE;

--계정 삭제
DROP USER SAMPLE CASCADE;

--USER 비밀번호 변경
ALTER USER SAMPLE IDENTIFIED BY pw1234;