--행 순서 관련함수

--lead() : 하위 행의 값을 상위 행에 출력함
--lag() : 상위 행의 값을 하위 행에 출력함

CREATE TABLE EMP_INFO(
    EMP_NO VARCHAR2(3),  --사원번호
    NAME VARCHAR2(20),   --사원이름
    SAL NUMBER           --급여(달러)
);

INSERT INTO EMP_INFO VALUES('100', '임예은', 24000);
INSERT INTO EMP_INFO VALUES('101', '이나경', 7000);
INSERT INTO EMP_INFO VALUES('102', '서지훈', 8000);
INSERT INTO EMP_INFO VALUES('108', '박채희', 12000);
INSERT INTO EMP_INFO VALUES('109', '이가은', 6000);
INSERT INTO EMP_INFO VALUES('110', '손흥민', 15000);
INSERT INTO EMP_INFO VALUES('111', '김민재', 21000);
INSERT INTO EMP_INFO VALUES('112', '이강인', 16000);
INSERT INTO EMP_INFO VALUES('113', '황희찬', 9000);
INSERT INTO EMP_INFO VALUES('119', '조규성', 13000);

COMMIT;

SELECT * FROM EMP_INFO;

--LEAD()
--SAL2 : 3행 위로 출력함
--SAL3 : NULL인 경우 0으로 표기할 수 있도록 추가
SELECT EMP_NO, NAME, SAL, 
       LEAD(SAL, 3) OVER(ORDER BY SAL DESC) SAL2,
       LEAD(SAL, 3, 0) OVER(ORDER BY SAL DESC) SAL3
FROM EMP_INFO;

--LAG()
--SAL2 : 3행 아래로 출력함
--SAL3 : NULL인 경우 0으로 표기할 수 있도록 추가
SELECT EMP_NO, NAME, SAL, 
       LAG(SAL, 3) OVER(ORDER BY SAL DESC) SAL2,
       LAG(SAL, 3, 0) OVER(ORDER BY SAL DESC) SAL3
FROM EMP_INFO;